# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  chisel = {
    pname = "chisel";
    version = "8a1f1b66e5e87dff6c8356fae346eb46512756cf";
    src = fetchFromGitHub {
      owner = "chipsalliance";
      repo = "chisel";
      rev = "8a1f1b66e5e87dff6c8356fae346eb46512756cf";
      fetchSubmodules = false;
      sha256 = "sha256-pB8kzqUmvHTG2FqRRjqig1FK9pGYrgBDOOekCqkwrsE=";
    };
    date = "2025-01-25";
  };
}
